# Generated by Django 3.2.6 on 2021-08-27 00:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210826_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
