# Generated by Django 3.2.6 on 2021-08-27 00:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_myproject_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
