# Generated by Django 3.2.6 on 2021-08-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_myproject_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproject',
            name='extra_image',
        ),
        migrations.AddField(
            model_name='myproject',
            name='demo',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
